# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\"\x1d\n\rScrapeRequest\x12\x0c\n\x04urls\x18\x01 \x03(\t\"t\n\x0eScrapeResponse\x12\x30\n\x0cscraped_urls\x18\x01 \x03(\x0b\x32\x1a.ScrapeResponse.ScrapedUrl\x1a\x30\n\nScrapedUrl\x12\x10\n\x08\x62\x61se_url\x18\x01 \x01(\t\x12\x10\n\x08rtsp_url\x18\x02 \x01(\t24\n\x07Scraper\x12)\n\x06Scrape\x12\x0e.ScrapeRequest\x1a\x0f.ScrapeResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCRAPEREQUEST._serialized_start=13
  _SCRAPEREQUEST._serialized_end=42
  _SCRAPERESPONSE._serialized_start=44
  _SCRAPERESPONSE._serialized_end=160
  _SCRAPERESPONSE_SCRAPEDURL._serialized_start=112
  _SCRAPERESPONSE_SCRAPEDURL._serialized_end=160
  _SCRAPER._serialized_start=162
  _SCRAPER._serialized_end=214
# @@protoc_insertion_point(module_scope)
