version: '3.8'

services:
  rtsp-server:
    container_name: 'rtsp-server'
    image: 'aler9/rtsp-simple-server:latest'
    volumes:
      - $PWD/rtsp-simple-server.yml:/rtsp-simple-server.yml
    ports:
      - '8554:8554'
      - '1935:1935'
      - '8888:8888'
      - '9997:9997'
  scrape-service:
    container_name: 'scrape-service'
    image: arm64v8/ubuntu
    command: tail -F anything
    #venv/bin/python3 -m uvicorn server:app --reload --port 8081
    ports:
    - '8081:8081'
    volumes:
      - ../:/app
